name: Java CI with SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Set up SonarQube Scanner CLI
        run: |
          docker pull sonarsource/sonar-scanner-cli:latest

      - name: Run SonarQube analysis
        run: |
          docker run --rm \
            -e SONAR_LOGIN="${{ secrets.SONAR_LOGIN }}" \
            -e SONAR_PASSWORD="${{ secrets.SONAR_PASSWORD }}" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli:latest

