name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        ports:
          - 9000:9000
        options: --health-cmd "curl -f http://localhost:9000/ || exit 1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and analyze with SonarQube
        run: |
          docker run --rm \
            -e SONAR_TOKEN \
            -v $(pwd):/usr/src \
            -w /usr/src \
            sonarsource/sonar-scanner-cli

